# please build
language: ruby
rvm:
  - 1.8.7
services:
 - redis-server
before_install:
  - sudo apt-get install -qq libgeoip-dev
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-i686.tar.bz2
  - tar -xf phantomjs-1.7.0-linux-i686.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.7.0-linux-i686 /usr/local/phantomjs
before_script:
  - rake db:test:load
  - git clone --depth=100 --quiet git://github.com/allourideas/pairwise-api.git
  - cd ./pairwise-api
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake util:useradd[pairwisetest@dkapadia.com,wheatthins]
  - bundle exec rake util:useradd[photocracytest@dkapadia.com,saltines]
  - bundle exec ./script/server -p 4000
  - cd ../
script: bundle exec spec spec/integration spec/controllers/questions_controller_spec.rb && bundle exec cucumber --no-profile --require features --require lib features/voting/voting.feature
bundler_args: --local
