version: "3.9"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:13
    network_mode: host
    restart: always
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .plausible-env

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    network_mode: host
    restart: always
    env_file:
      - .plausible-env
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:stable
    network_mode: host
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .plausible-env

  mysql_db:
    image: mysql:8.0
    restart: always
    network_mode: host
    env_file:
      - .mysql-env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db-data:/var/lib/mysql

  redis_db:
    image: redis:6.2.7-alpine
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .plausible-env
    command: redis-server --save 20 1 --loglevel warning
    network_mode: host
    volumes:
      - redis-db-data:/data

  allourideas-web:
    container_name: allourideas-web
    restart: always
    env_file: .allourideas-env
    build:
      context: ./allourideas-web/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - all-our-ideas:/home
    healthcheck:
      test: ["CMD", "curl", "-f", "https://${FULL_HOSTNAME}/"]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "2000"
        max-size: "25m"

  pairwise-api:
    container_name: pairwise-api
    restart: always
    env_file: .pairwise-env
    build:
      context: ./pairwise-api/
      dockerfile: Dockerfile
    ports:
      - "3072:3072"
    volumes:
      - pairwise-api:/home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${FULL_HOSTNAME}:3072/"]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "2000"
        max-size: "25m"

  #certbot:
  #  image: certbot/certbot
  #  container_name: certbot
  #  env_file: .env
  #  volumes:
  #    - certbot-env:/etc/letsencrypt
  #    - certbot-var:/var/lib/letsencrypt
  #    - web-root:/var/www/html
  #  depends_on:
  #    - webserver

volumes:
  all-our-ideas:
    driver: local
  pairwise-api:
    driver: local
  pg-db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
  mysql-db-data:
    driver: local
  redis-db-data:
    driver: local
  certbot-var:
  certbot-env:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: webserver/letsEncryptCerts


