development:
    HOST: localhost:3001
    API_HOST: http://localhost:3000
    PAIRWISE_USERNAME: pairwisetest@dkapadia.com
    PAIRWISE_PASSWORD: wheatthins
    PHOTOCRACY_USERNAME: photocracytest@dkapadia.com
    PHOTOCRACY_PASSWORD: saltines
    PHOTOCRACY_HOST: photocracy:3001
    IP_ADDR_HASH_SALT: 2039d9ds9ufsdioh2394230 #prevent dictionary attacks on stored ip address hashes

production:
    HOST: <%= ENV['ALLOURIDEAS_HOST'] %>
    API_HOST: <%= ENV['API_HOST'] %>
    PAIRWISE_USERNAME: <%= ENV['PAIRWISE_USERNAME'] %>
    PAIRWISE_PASSWORD: <%= ENV['PAIRWISE_PASSWORD'] %>
    IP_ADDR_HASH_SALT: <%= ENV['IP_ADDR_HASH_SALT'] %> #prevent dictionary attacks on stored ip address hashes

    PHOTOCRACY_USERNAME: <%= ENV['PHOTOCRACY_USERNAME'] %>
    PHOTOCRACY_PASSWORD: <%= ENV['PHOTOCRACY_PASSWORD'] %>
    PHOTOCRACY_HOST: photocracy.org

staging:
    HOST: <%= ENV['STAGING_ALLOURIDEAS_HOST'] %>
    API_HOST: <%= ENV['STAGING_API_HOST'] %>
    PAIRWISE_USERNAME: <%= ENV['PAIRWISE_USERNAME'] %>
    PAIRWISE_PASSWORD: <%= ENV['PAIRWISE_PASSWORD'] %>

    PHOTOCRACY_USERNAME: <%= ENV['PHOTOCRACY_USERNAME'] %>
    PHOTOCRACY_PASSWORD: <%= ENV['PHOTOCRACY_PASSWORD'] %>
    PHOTOCRACY_HOST: photocracy.org

    IP_ADDR_HASH_SALT: <%= ENV['IP_ADDR_HASH_SALT'] %> #prevent dictionary attacks on stored ip address hashes

test:
    HOST: localhost
    API_HOST: http://localhost:4000

    PAIRWISE_USERNAME: testing@dkapadia.com
    PAIRWISE_PASSWORD: wheatthins

cucumber:
    HOST: localhost
    # Use a different test database / server for test purposes
    API_HOST: http://localhost:4000
    PAIRWISE_USERNAME: testing@dkapadia.com
    PAIRWISE_PASSWORD: wheatthins
    PHOTOCRACY_USERNAME: photocracytest@dkapadia.com
    PHOTOCRACY_PASSWORD: saltines
    IP_ADDR_HASH_SALT: 2039d9ds9ufsdioh2394230 #prevent dictionary attacks on stored ip address hashes
    PHOTOCRACY_HOST: photocracy.org
