# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql2
  database: <%= ENV['AOI_MYSQL_DATABASE'] %>
  username: <%= ENV['AOI_MYSQL_USER'] %>
  password: <%= ENV['AOI_MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000
  collation: utf8_general_ci
  host: <%= ENV['AOI_MYSQL_HOST'] %>

production:
  adapter: mysql2
  database: <%= ENV['AOI_MYSQL_DATABASE'] %>
  username: <%= ENV['AOI_MYSQL_USER'] %>
  password: <%= ENV['AOI_MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000
  collation: utf8_general_ci
  host: <%= ENV['AOI_MYSQL_HOST'] %>
  port: <%= ENV['AOI_MYSQL_PORT'] %>

test: &test
  database: pairwise_test

cucumber:
  <<: *test

